spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RBAC?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: zxcvbnm1-
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:Mapper/*.xml
server:
  port: 8088